import numpy as np
one_array=np.ones((2,3))
zero_array=np.zeros((2,3))
empty_array=np.empty((2,3))
print("zero:\n",one_array)
print("zero:\n",zero_array)
print("empty:\n",empty_array)
arr=np.array([[1,2,3],[4,5,6]])
print("shape of array:",arr.shape)
reshaped=arr.reshape(3,2)
print("reshaped array:\n",reshaped)
arr1=np.array([1,2,3])
copy_arr1=arr1.copy()
view_arr1=arr1.view()
print("original:",arr1)
print("copy:",copy_arr1)
print("view:",view_arr1)
arr2=np.array([1,2])
arr3=np.array([3,4])
concatenated=np.concatenate ((arr2,arr3))
print("concatenated array:",concatenated)
arr4=np.array([5,2,9,1])
print("sorted array:",np.sort(arr4))